### ISSUE TITLE
Using Currency Format for Range

### ISSUE THREAD

**Issue by omer-sds** [ruskid/yii2-nouislider#1]
Hi how can i specify `format` property fto format the slider with currency, i see there is a js option like this
`format: wNumb({
		decimals: 0
	}),`

i tried these 2 options but got error both times
1. `'format' => new yii\web\JsExpression ( 'wNumb({decimals: 2})' ) ,`

> Error : ReferenceError: wNumb is not defined

and then 

`'format'=>[
                                                        'wNumb'=>[
                                                            'decimals'=>2
                                                        ]
                                                    ],`

> Error : Error: noUiSlider (10.0.0): 'format' requires 'to' and 'from' methods.

Thing to be noted , in `renderSlider()` method inside the `Slider.php` widget class the js options are initialized as follows

`{"start":[12000],"connect":true,"format":wNumb({decimals: 2}),"range":{"min":12000,"max":70000}}`

i am calling the widget like this 
```
Slider::widget ( [
'name' => 'price-range' ,
'value' => 12000 ,
'pluginOptions' => [
  'start' => [12000 ] ,
  'connect' => true ,
  'format' => new yii\web\JsExpression ( 'wNumb({decimals: 2})' ) ,
  'range' => [
    'min' => 12000 ,
    'max' => 70000
    ]
 ]
] )
```

**Comment by ruskid** [comment]
Don't need it yet and have no time. Maybe in near future will take a look.
You are welcome to collaborate. 
Thanks for the issues.

**Comment by ruskid** [comment]
My final solution was like this. 
```php
'format' => [
                'from' => new JsExpression('function(v) {
                    return v;
                }'),
                'to' => new JsExpression('function(v) {
                    return v * 2;
                }'),
            ],
```
It's not required to use wNumb library and your issue is related to noUislider.
