### ISSUE TITLE
Issue with providing id attribute with -

### ISSUE THREAD

**Issue by omer-sds** [ruskid/yii2-nouislider#2]
if you try to provide the id in the format
```
  Slider::widget ( [
     'name' => 'price-range' ,
     'id'=>'price-range',
```

it gives you javascript error 

> SyntaxError: missing ; before statement
var eval(price-range_nouislider) = document.getElementById("price-ra

i recon it the line number 101 in Slider.php at the following statement
`$js = "var $sliderId = document.getElementById('$sliderId'); noUiSlider.create($sliderId, $jsOptions);";`

**Comment by ruskid** [comment]
Because of using dashes in "id". Javascript variables can't contain dashes. **var $sliderId**

Basically now I stupidly strip all special characters from id.
```php
$this->javascriptSliderId = preg_replace('/[^a-zA-Z]+/', '', $this->id);
```
You can set your own javascriptSliderId to call it later and change it's behavior.
